apiVersion: v1
kind: Service
metadata:
  name: system-monitor-service
spec:
  type: NodePort
  selector:
    app: system-monitor
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
