apiVersion: v1
kind: Service
metadata:
  name: system-monitor-service
  labels:
    app: system-monitor
spec:
  type: NodePort
  selector:
    app: system-monitor
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080
