replicaCount: 1

image:
  repository: manmohangpt08/system-monitor
  tag: "1"
  pullPolicy: Always

service:
  type: NodePort
  port: 8080
  targetPort: 8080
  nodePort: 30080

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"
